import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
  archivSidebar: [
    {
        type: 'doc',
        id: 'archiv/intro',
    },
    {
        type: 'category',
        label: '2020 bis heute',
        link: {
            type: 'generated-index',
            title: '2020 bis heute',
            description: 'Was passiert in dem Jahrzehnt, das mit der großen Corona-Pandemie begonnen hat?',
            slug: '/category/2020-heute',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
        items: [
            {
                type: 'autogenerated',
                dirName: 'archiv/2020-heute', // Generate sidebar slice from docs/archiv/2020-heute
            },
        ],
    },
    {
        type: 'category',
        label: '2010 bis 2019',
        link: {
            type: 'generated-index',
            title: '2010 bis 2019',
            description: 'Die 10er-Jahre des neuen Jahrtausends sind geprägt von internationalen Chorwettbewerben in ganz Europa.',
            slug: '/category/2010-2019',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
        items: [
            {
                type: 'autogenerated',
                dirName: 'archiv/2010-2019',
            },
        ],
    },
    {
        type: 'category',
        label: '2000 bis 2009',
        link: {
            type: 'generated-index',
            title: '2000 bis 2009',
            description: 'Das neue Jahrtausend beginnt mit einem großen Fest zum 100. Geburtstag der Frohen Stunde Weroth.',
            slug: '/category/2000-2009',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
        items: [
            {
                type: 'autogenerated',
                dirName: 'archiv/2000-2009',
            },
        ],
    }
    ]
};

export default sidebars;
