import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
  archivSidebar: [
    {
        type: 'category',
        label: '2020 bis heute',
        items: [
            {
                type: 'autogenerated',
                dirName: 'archiv/2020-heute', // Generate sidebar slice from docs/archiv/2020-heute
            },
        ],
    },
    {
        type: 'category',
            label: '2010 bis 2019',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'archiv/2010-2019',
                },
            ],
        },
    {
        type: 'category',
            label: '2000 bis 2009',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'archiv/2000-2009',
                },
            ],
        }
    ]
};

export default sidebars;
